---
title: "p8105_hw5_lvr2115"
author: "Laura Robles-Torres"
date: "2023-11-13"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(ggplot2)
library(rvest)
```

 
## Problem 2

Import and tidy data

```{r import and tidy,message=FALSE,warning=FALSE}

raw_data = 
  tibble(
    files = list.files("./data"),
    path = str_c("./data/", files)
  ) |>
  mutate(data = map(path, read_csv)) |>
  unnest(data) 

tidy_data =
  raw_data |> 
   janitor::clean_names() |> 
   separate(files, sep="_", into = c("study_arm", "subject_id")) |>
   separate(subject_id, sep=".csv", into=c("subject_id")) |>
   mutate(study_arm = recode(study_arm, "con" = "Control", "exp" = "Experiment")) |>
   pivot_longer(
    cols = starts_with("week"),
    names_prefix = "week_",
    names_to = "week_num",
    values_to = "obs"
  ) |>
  mutate(
     week_num = as.numeric(week_num)) |>
  select(study_arm, subject_id, week_num, obs)
```

Make a spaghetti plot showing observations on each subject over time, and comment on differences between groups.

```{r plot}
ggplot(tidy_data, aes(x = week_num, y = obs , color = subject_id)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ study_arm) +
  labs(
    x = "Week", 
    y = "Observed value",
    title = "Changes in observed value per study arm over time"
  ) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```


